### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by GrantPerkins** [Team1100/LunacyVEX#1]
I don't have permission to push to this repository even though it was made especially for my code. Can someone please change my permissions?

**Comment by SupremeSteak1** [comment]
I added you as a collaborator. Let me know if that fixes it.

**Comment by GrantPerkins** [comment]
Fixed, I think most of the problem was that I am bad at git.

**Comment by SupremeSteak1** [comment]
Well, now you are better at git!
